import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "~/utils/trpc";

const AdminApplicationsIndexPage: NextPage = () => {
  const applications = trpc.admin.applications.all.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          App/Applications Page
        </h1>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {applications.data?.map((application) => (
            <div key={application.id}>
              <Link href={`/applications/${application.id}`}>
                <strong>{application.name}</strong>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default AdminApplicationsIndexPage;
