import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEventHandler } from "react";
import { trpc } from "~/utils/trpc";

const Home: NextPage = () => {
  const router = useRouter();
  const createApplication = trpc.admin.applications.create.useMutation();

  const handleSubmit: FormEventHandler<HTMLFormElement> = async (evt) => {
    evt.preventDefault();
    const formData = new FormData(evt.currentTarget);
    const name = formData.get("name");
    const baseUrl = formData.get("subdomain");
    const description = formData.get("description");
    if (typeof name !== "string") {
      return;
    }
    if (typeof baseUrl !== "string") {
      return;
    }
    if (typeof description !== "string") {
      return;
    }
    const response = await createApplication.mutateAsync({
      name,
      baseUrl,
      description,
    });

    if (response.id) {
      router.push("/applications");
    }
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          App/Applications/New Page
        </h1>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          <form onSubmit={handleSubmit}>
            <div>
              <label>
                Application Name
                <input id="name" name="name" placeholder="Application Name" />
              </label>
            </div>
            <div>
              <label>
                Application Name
                <textarea
                  id="description"
                  name="description"
                  placeholder="What is your application about?"
                ></textarea>
              </label>
            </div>
            <div>
              <label>
                Subdomain
                <input id="subdomain" name="subdomain" />
              </label>
            </div>
            <div>
              <button type="submit">Create Application</button>
            </div>
          </form>
        </div>
      </main>
    </>
  );
};

export default Home;
